// Code generated by gen, DO NOT EDIT.

package dialogs

import (
	"context"

	"golang.org/x/xerrors"

	"github.com/gotd/td/tg"
)

// No-op definition for keeping imports.
var _ = context.Background()

// Request is a parameter for Query.
type Request struct {
	Limit int
}

// Query is a abstraction for dialogs request.
// NB: iterator mutates returned data (sorts, at least).
type Query interface {
	Query(ctx context.Context, req Request) (tg.MessagesDialogsClass, error)
}

// QueryFunc is a function adapter for Query.
type QueryFunc func(ctx context.Context, req Request) (tg.MessagesDialogsClass, error)

// Query implements Query interface.
func (q QueryFunc) Query(ctx context.Context, req Request) (tg.MessagesDialogsClass, error) {
	return q(ctx, req)
}

// QueryBuilder is a helper to create message queries.
type QueryBuilder struct {
	raw tg.Invoker
}

// NewQueryBuilder creates new QueryBuilder.
func NewQueryBuilder(raw tg.Invoker) *QueryBuilder {
	return &QueryBuilder{raw: raw}
}
