name: E2E
on:
  push:
    tags:
      - v*
    branches:
      - main
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2.1.3
        with:
          go-version: 1.16

      - name: Install latest mtg proxy
        run: go get github.com/gotd/mtg@master

      - name: Checkout latest code
        uses: actions/checkout@v2.3.4

      # Note that we deliberately don’t restore GOCACHE.
      # That is, we must not cache e2e test results.
      - name: Get Go environment
        id: go-env
        run: echo "::set-output name=modcache::$(go env GOMODCACHE)"
      - name: Set up cache
        uses: actions/cache@v2.1.4
        with:
          path: ${{ steps.go-env.outputs.modcache }}
          key: e2e-${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: e2e-${{ runner.os }}-go-

      - name: Download dependencies
        run: go mod download && go mod tidy

      # Run all tests that starts with "TestExternalE2E".
      - name: Run tests
        run: go test -v -run ^TestExternalE2E ./...
        env:
          GOTD_TEST_EXTERNAL: 1
          GOTD_MTPROXY_ADDR: "localhost:3128"
