name: Nightly
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update-schema:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout latest code
        uses: actions/checkout@v2.3.4

      - name: Install Go
        uses: actions/setup-go@v2.1.3
        with:
          go-version: '1.16.1'

      - name: Download dependencies
        run: go mod download

      - name: Update schema
        run: make download_schema download_e2e_schema

      - name: Generate files
        run: make generate

      - name: Create PR
        id: cpr
        uses: peter-evans/create-pull-request@v3.8.2
        with:
          author: GitHub <actions@github.com>
          committer: GitHub <actions@github.com>
          commit-message: 'chore: update schema'
          branch: pr/update-schema
          delete-branch: true

          title: Update schema
          body: |
            Update Telegram API schema.
          labels: |
            dependencies

      - name: 'Print PR ${{ steps.cpr.outputs.pull-request-number }} URL'
        if: ${{ steps.cpr.outputs.pull-request-operation != '' }}
        run: echo '${{ steps.cpr.outputs.pull-request-url }}'
